### ISSUE TITLE
GET http://127.0.0.1:1880/uibuilder/vendor/jquery/dist/jquery.min.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by kevin-smets** [TotallyInformation/node-red-contrib-uibuilder#39] opened 2018-12-28 20:26 UTC
Software       | Version
-------------- | -------
Node.JS        |  v8.12.0
npm            |  6.4.1
Node-RED       |  v0.19.5
uibuilder node | 1.0.8
uibuilderFE    | 1.0.8
OS             | MacOS 10.13.6
Browser        |  Chrome 71

### How is Node-RED installed? Where is uibuilder installed?

Installed as an npm package, started through an npm script.

userDir set to ./.node-red (by using settings.js) of my working directory to have a complete standalone installation. Instead of running it globally.

Vendor paths are set correctly when starting node-red:

```
info: UIbuilder: Adding master vendor path url=/uibuilder/vendor/normalize.css, path=/Users/kevin/git/home2/node_modules/normalize.css
info: UIbuilder: Adding master vendor path url=/uibuilder/vendor/jquery, path=/Users/kevin/git/home2/node_modules/jquery/dist
```

localhost:1880/uibuilder/ also routes correctly to the index.html

However, in the [template index.html](https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/f2657847f8478b512f9a623449907f69612bf87f/nodes/templates/index.html#L83) the line reads dist/jquery.min.js causing a 404. When removing the dist from the path, it works as expected.

**Comment by TotallyInformation** [comment] 2018-12-28 22:18
Hi Kevin, many thanks for reporting that. I've fixed it and published v1.0.10 which also brings minor updates to dependencies.

**Comment by TotallyInformation** [comment] 2018-12-28 22:38
I might add the tags if I knew how!?

By "vuejs template" I assume you mean the WIKI example? If so, please feel free to amend directly, you should have access I think. If not, I'll give you access.

**Comment by kevin-smets** [comment] 2018-12-30 22:07
Awesome, thanks again!

**Comment by Lurow** [comment] 2019-01-22 14:05
Hi there,

I had the same problem, checked the install path and it was indeed `node_modules/jquery/dist/jquery.min.js`

nonetheless, I had to remove the `dist` from my index.html to get it working again.

**Comment by TotallyInformation** [comment] 2019-01-22 20:38
Hi @Lurow , thanks for responding. Are you able to show me the folder structure?

I can't understand at the moment why, if jQuery is in the right location, the link isn't working for you. I am interested to see if there is another copy of jQuery at `node_modules/jquery/jquery.min.js`

**Comment by TotallyInformation** [comment] 2019-02-04 10:54
I've now seen the same issue but I cannot work out why. Some installations have to use the dist path and some do not!

This is adding fuel to my thoughts about switching the default template to a different library - probably VueJS. I think that I will create templates for several libraries actually.

In the meantime, v1.1.0 is the next major version (might even end up being v2.0.0) and that at least has an additional comment in the index.html file indicating both the problem and the workaround. Check out the [adminui-editor branch](https://github.com/TotallyInformation/node-red-contrib-uibuilder/tree/adminui-editor) to see the updated file.

**Comment by TotallyInformation** [comment] 2019-03-03 02:34
Still not entirely clear why this might be happening. Is suspect (but cannot prove) that it is a weird npm/node_modules issue.

It is also possible that I've inadvertently fixed it with other fixes in v2.

As I haven't managed to make any progress and because I intend to switch from jquery/normalize.css to VueJS/bootstrap-vue in v2 of uibuilder, I'm afraid I must close this again.

If anyone finds any more info - please feel free to reopen.

**Closed by TotallyInformation** 2019-03-03 02:35 UTC

**Comment by TotallyInformation** [comment] 2019-03-04 20:04
:sigh: as with so many things, in trying to fix a different issue, I worked out what causes this one.

The problem is that if uibuilder is accessing a package installed with uibuilder, that package is in a different place, not `<userDir>/node_modules`. In order to try and work out where it is so that I can add a static server path to it, there are 2 different lookups. The first, main lookup finds things installed in `<userDir>/node_modules`, e.g. if you installed them as a user. The second finds things installed anywhere (uses `require.resolve(packageName)`). It is this 2nd one that gives odd results. It finds the location of the script defined in `package.json` as "main" but this may not be where the front-end scripts are.

So, if you install jquery yourself, that's one path but if you use the version installed by uibuilder, that is a different one. That isn't always going to work as it may give inconsistent results.

So in v2, I will be using a different strategy and my own packageFind function. This is implemented now in the v2 branch if you want to test it.
