### ISSUE TITLE
not seeing icons and getting error in console running example

### ISSUE THREAD

**Issue by wegunterjr** [TotallyInformation/node-red-contrib-uibuilder#213] opened 2023-05-09 02:44 UTC
Before logging an issue, please make sure that you are either on the latest npm version or the latest GitHub version.

Please ensure that as much of the following information is included as possible.

### Software and Package Versions

> Node.JS, Node-RED and uibuilder back-end versions are listed in the Node-RED log on startup. 
  `npm --version` shows the installed version of npm.
  From your browser's developer console (F12), the uibuilder front-end
  version can be seen by issuing the command `uibuilder.get('version').
  Please include all 5. Node.JS needs to be at least 4 but realistically, anything less than 6 is unlikely to work.

> Please also include your Operating System name and version and your browser's name and version. Any browser version less than n-2 or IE < v11 very unlikely to work without help from [polyfill.io](https://polyfill.io).

> I know it seems like a lot but it saves time in the long run

Software       | Version
-------------- | -------
Node.JS        | v16.16
npm            |   9.6.4
Node-RED       | 3.0.2
uibuilder node | 6.4.1
uibuilderFE    | plain html (no vue)
OS             | Ubuntu 22.04.1 LTS 
Browser        | chrome

### How is Node-RED installed? Where is uibuilder installed?

node red is a docker container - lates
uibuilder is installed using package manager

Running the example found in this link:
https://flows.nodered.org/flow/89487d20c635d54d9b98d963656ce429

`Uncaught TypeError: uibuilder._uiComposeComponent is not a function`

**Comment by TotallyInformation** [comment] 2023-05-10 18:39
Hmm, interesting. I can reproduce this. Let me explore.

**Comment by TotallyInformation** [comment] 2023-05-10 19:36
Found the issue. Entirely my fault. In the last release, I updated the client library - moving all of the ui processing to its own external class library. In doing so, the internal functions (those starting with `_`) where properly hidden from the uibuilder client object. Since I foolishly used one of those internal functions in this example, it no longer works of course.

However, the work-around only requires 8 lines of code. So please replace your `index.js` file with this one.

```javascript
// @ts-nocheck
/** Dynamic SVG example */

// uibuilder.logLevel = 1

/** A clone of the uibuilder $ function so you don't have to install v6.2-dev
 * Simplistic jQuery-like document CSS query selector, returns an HTML Element
 * If the selected element is a <template>, returns the first child element.
 * type {HTMLElement}
 * @param {string} cssSelector A CSS Selector that identifies the element to return
 * @returns {HTMLElement|HTMLTemplateElement|null}
 */
function mySelector(cssSelector) {
    let el = document.querySelector(cssSelector)

    if (!el) {
        log(1, 'mySelector', `No element found for CSS selector ${cssSelector}`)()
        return null
    }

    if (el.nodeName === 'TEMPLATE') {
        el = el.content.firstElementChild
        if (!el) {
            log(0, 'mySelector', `Template selected for CSS selector ${cssSelector} but it is empty`)()
            return null
        }
    }

    return el
}

function doMe(event) {
    uibuilder.eventSend(event)
}

/** Insert a clone of a template tag
 * NB: Template should have only a single direct child tag, nothing other than that tag and its contents will be cloned.
 * @param {HTMLTemplateElement} template The template to clone and insert
 * @param {HTMLElement} parent The parent within which to insert the clone
 * @param {object} [ui] Optional uib UI object that will apply changes to the cloned element (e.g. attribs, slot)
 */
function htmlClone(template, parent, ui) {
    console.log(ui)
    if (!template || !(template instanceof Element)) {
        console.error('Template HTMLElement not provided or is not an HTML Element')
        return
    }
    if (!parent || !(parent instanceof Element)) {
        console.error('Parent HTMLElement not provided or is not an HTML Element')
        return
    }
    if (!ui) ui = {}
    if (!ui.position) ui.position = 'last'

    const clone = template.cloneNode(true)

    // Oops! Fns starting with `_` should not have been used - sorry. This fn no longer available directly.
    // Will add an equivalent in a future release (post v6.4.1) probably called `uiEnhanceElement`
    // uibuilder._uiComposeComponent(clone, ui)
    clone.id = ui.id
    clone.classList.add(ui.attributes['data-posn'])
    clone.dataset.state = ui.attributes['data-state']
    clone.dataset.posn = ui.attributes['data-posn']
    clone.onclick = doMe //uibuilder.eventSend

    if (ui.position === 'first') {
        // Insert new el before the first child of the parent. Ref: https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore#example_3
        parent.insertBefore(clone, parent.firstChild)
    } else if (Number.isInteger(Number(ui.position))) {
        elParent.insertBefore(clone, parent.children[ui.position])
    } else {
        // Append to the required parent
        parent.appendChild(clone)
    }

}
const x = {
    "id": "bulb1",
    "attributes": {
        "class": "bulb posn1",
        "data-state": "off",
        "data-posn": "posn1"
    },
    "events": {
        "click": "uibuilder.eventSend"
    },
    "position": "last"
}

// The Template tag in index.html contains a template "bulb" SVG image
// Here, we clone that multiple times and set some properties.
// Note that `htmlClone` is a function that will land in the uibuilder client in v6.2
// Also, the $ function is improved in v6.2 so a copy of that is included here for convenience.
//
// We track state and position class on data-* attributes so that it is much easier to process
// click events in Node-RED without having to create a custom click handler, we can just use the standard eventSend.
// CSS classes do all the clever stuff 😁

htmlClone($('#bulb-template'), $('#floorplan'), {
    // As always, we set a unique ID for every created element so it can be updated easily later
    id: 'bulb1',
    // You only need this if you want to choose 'first' or a position number,
    // the clone will be added at the specified child position of the parent.
    // position: 'last', 
    attributes: {
        // Apply base bulb class and a positioning class
        class: 'bulb posn1',
        // Track the on/off state separately - makes processing in Node-RED easier
        'data-state': 'off',
        // Track the position class separately - makes processing in Node-RED easier
        'data-posn': 'posn1'
    },
    // We have to add event handlers after a clone, they cannot be included in the template
    events: {
        click: 'uibuilder.eventSend'
    }
})

htmlClone(mySelector('#bulb-template'), mySelector('#floorplan'), {
    id: 'bulb2',
    attributes: {
        class: 'bulb posn2',
        'data-state': 'off',
        'data-posn': 'posn2'
    },
    events: {
        click: 'uibuilder.eventSend'
    }
})

htmlClone(mySelector('#bulb-template'), mySelector('#floorplan'), {
    id: 'bulb3',
    attributes: {
        class: 'bulb posn3',
        'data-state': 'off',
        'data-posn': 'posn3'
    },
    events: {
        click: 'uibuilder.eventSend'
    }
})

htmlClone(mySelector('#bulb-template'), mySelector('#floorplan'), {
    id: 'bulb4',
    attributes: {
        class: 'bulb posn4',
        'data-state': 'off',
        'data-posn': 'posn4'
    },
    events: {
        click: 'uibuilder.eventSend'
    },
})
```

That will continue to work even after I've updated the client since it just uses vanilla JavaScript instead of the ui function. I will add a new function, `uibuilder.uiEnhanceElement` in a future release which will use the internal `_ui._uiComposeComponent` function correctly.

Also please note another small error. This time in the flow. The flow contains a comment saying that you should create the background SVG file as `background1.svg` but it should be `background.svg`.

I will update the flow with both fixes as soon as I can but in the meantime, the above work-arounds should be fine.

Sorry for the mistakes. And thanks for reporting the problem. 

Regards, J.

**Comment by wegunterjr** [comment] 2023-05-10 23:09
ah..rock on!  k. I used the above code and it's working as expected. I now see the light bulbs and can interact with them. Way cool!   

Thank you!

**Comment by TotallyInformation** [comment] 2023-05-11 11:44
Going to close the issue for now since I've updated the example with the work-around and will be adding the new function to the next release.

**Closed by TotallyInformation** 2023-05-11 11:44 UTC
Labels: bug, Workaround Available
