### ISSUE TITLE
Slow Reployment when using projects

### ISSUE THREAD

**Issue by canbaytok** [TotallyInformation/node-red-contrib-uibuilder#178] opened 2022-04-27 05:20 UTC
Software       | Version
-------------- | -------
Node.JS        | Latest Node-RED Docker Image
npm            | Latest Node-RED Docker Image
Node-RED       | Latest Node-RED Docker Image
uibuilder node | 5.0.2
uibuilderFE    | 5.0.2
OS             | Ubuntu 18.04.6 LTS
Browser        | Chrome 100.0.4896.127

### How is Node-RED installed? Where is uibuilder installed?
Node-RED runs insinde a Docker container. uibuilder is installed directly from Node-REDs palette

### Issue
I recently updated uibuilder to version 5.0.2 and after some inital issues with preexisting middleware configs (sioUse.js, etc.; deleting those fixed it right away) I noticed that redeployments of Node-RED took a very long time to process.
After some digging I noticed that since I am using Node-RED projects feature to save my flow in a git-repo and uibuilder saves the necessary packages inside the uibuilder/ directory now, every single file inside those packages (vue, bootstrap-vue and many more) ended up getting checked for a commit slowing down redeployments.

### Solution
Adding

> uibuilder/node_modules/
uibuilder/package.json
uibuilder/package-lock.json

to a .gitignore file fixed the issue immediately, but unfortunately I am quite unsure whether this a valid fix (it should be in my mind, since these files/directories were not commited by git in previous installations and no problems occured).

I would love to get some feedback on this topic!

(Sorry if this issue is unnecessary. I searched through the Wiki and Tech Docs, but could not find a page related to this)

**Comment by xly01** [comment] 2022-04-27 05:21
来信已收到，感谢！                                     此致                         敬礼！Tel：13372509117（谢礼阳）

**Comment by TotallyInformation** [comment] 2022-04-27 08:53
Hi, thanks for reporting this.

Really, this is an issue with the Node-RED projects feature rather than uibuilder. It should be excluding `**/node_modules/` so that all `node_modules` folders are excluded - that is a standard exclusion for node.js apps. `package-lock.json` can also be excluded but actually it doesn't really matter.

I would suggest that you leave `package.json` in your commits since you would want it if you needed to restore.

Also worth noting that, as people move into more complex front-ends, they will also have package.json files and `node_modules` folders inside each instance folder. 

By the way, another workaround for your issue would also be to move the `uibRoot` folder to somewhere different. You can do that in settings.js. Personally, I wish that the project feature in Node-RED worked differently and included the userDir folder in the project. As it doesn't, you can only have 1 set of installed nodes and 1 settings.js file which greatly limits its usability, especially for uibuilder because it means that your front-end code folders are divorced from the flows that need them. Indeed, you may wish to consider at least creating a soft-link from the instance folder to your project folder so that at least the instance files can be committed with the flow. But it is a bit of a mess and personally, I avoid using projects mostly, I only have it turned on so that I can test uibuilder with it.

**Comment by canbaytok** [comment] 2022-04-27 10:03
Hi there,

thanks for the quick reply! You are right I should have kept the package.json file. I am not that experienced with nodejs projects, but my understand was that "npm install" can look at the contents of the package.json file and download necessary packages.

Updating my .gitignore file and creating an issue in the Node-RED repo to try and draw attention to this topic.

**Comment by TotallyInformation** [comment] 2022-05-08 14:19
> my understand was that "npm install" can look at the contents of the package.json file and download necessary packages

Sorry, I should have replied sooner.

Yes, it does do that. But the problem is that Node-RED does NOT install packages in the PROJECT folder but only in the userDir folder. So a project does not describe a node-red install, only the project flows and a few other things.

I will be trying to improve the uibuilder documentation for this but it isn't a uibuilder issue I'm afraid. None-the-less, well worth reporting so thanks for that.

**Closed** 2022-07-15 00:58 UTC
Labels: Documentation/Help, Upstream Bug, no-issue-activity
