### ISSUE TITLE
Uibuilder with url not 'uibuilder' not always connecting on android

### ISSUE THREAD

**Issue by colinl** [TotallyInformation/node-red-contrib-uibuilder#9] opened 2017-09-27 13:03 UTC
I have a uibuilder with riot app based on this sample code [1]. This works fine on PC and Chrome on Android except in one particular case. If on Android I browse to the location and then use the Add to Homescreen to put a startup icon on the home page and then I invoke it through the icon, after it has not been active for some time, then it often fails to connect (at least I think that is what is happening). It just sits there showing the page and dynamic data are not updated. If I refresh the screen then it starts correctly.  To get the failure it seems necessary to swipe the window away then wait several minutes and then re-open it.
I have another uibuilder node in the flow (at a different url) which does not use riot and is based on the sample that comes with the app and it does not exhibit the symptom. In fact I think that if I open the non-riot one first and then open the riot one then it connects ok, which is strange. Not absolutely certain about this as I am not sure exactly how long I have to wait between tries so I may just not have waited long enough.
I am trying to investigate further, any suggestions as to what might be causing it?

[1] https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/node-red/qjzt4Obvbm8/wVod_uvNAgAJ

**Edit** I was wrong in saying that if I opened the non-riot app first then the riot one connected, it doesnt make any difference. Also I have determined that if I wait 5 minutes after swiping the app away then it fails pretty consistently.

**Comment by colinl** [comment] 2017-09-27 15:39
Well, I wasn't expecting that!
It seems to be to do with the url. I removed the non-riot app and flow, which used the default url of uibuilder, and confirmed I still get the failure at the riot app url which is /home.
I then changed the url in the node to uibuilder and the folder name to uibuilder, but kept the flow and the app the same and now as far as I can determine it is working perfectly. Does that make any sense?

**Comment by colinl** [comment] 2017-09-27 21:06
I am out of ideas, I can't think of anything else to do.

**Comment by TotallyInformation** [comment] 2017-09-28 07:43
Sorry, I've been in Helsinki for a couple of days. If you are sure that the issue is related to the naming of the URL, my first thought would be that it will be something to do with Socket.IO. I do go to some lengths to try and make sure that each URL gets a separate Socket.IO channel - possibly there is something in there that only works consistently if using the default uibuilder namespace though I cannot think of anything in the logic that might cause that.

Really, I'd need a lot more debugging information from your Riot code to work out what Android cannot do that other browsers can. I've not really done enough with Riot to be really familiar with any foibles.

Also, it would be useful to see if the same thing happens with another front-end library such as MoonJS for example. (which is next on my list of FE libraries to try). You could also try going back to the template FE code and then putting Riot in yourself - so not using my example code - to see if that makes a difference.

I'm afraid that I don't use Android at all so I'm not really in a position to test things on that platform.

**Comment by colinl** [comment] 2017-09-28 08:16
No need to apologise, we all have lives to live. In fact I see now that it is nothing to do with riot, I see the same symptom on a non-riot uibuilder setup if the url is set to /home. I have changed the title appropriately.  I have tried it on a different phone and see the same issue so it is not something odd about my phone. Also it is not to do with multiple Socket.IO channels as it happens if the phone is the only connection. Can you suggest some debugging I can put it to try and diagnose it further? With debug logging enabled in the node I see absolutely nothing when the app opens on the phone.  I am not sure if I can make the browser on the phone startup with the console showing, but I will investigate that.

**Comment by colinl** [comment] 2017-09-28 14:50
OK, I have sussed it. It is necessary to have a manifest.json for Add to Homescreen to work correctly. Otherwise you get the symptom described here. Haven't the foggiest idea why. The default one that comes with the node works ok. My version at /uibuilder had a manifest.json but the one at /home does not.  I will do a PR for a tweak to the readme to say this.

**Comment by TotallyInformation** [comment] 2017-09-28 16:35
Ah, that makes sense now. There is a default manifest containing `"short_name": "uibuilder",` which I'm guessing is the problem.

Thanks for the PR. And thanks for tracking that one down.

**Comment by TotallyInformation** [comment] 2017-09-28 16:38
PR Merged. I think that I probably need to add some more info on this to the README or maybe add a wIKI entry referenced from the README. 

Anyway, I'll leave this open until I've published an update so that I remember.

**Comment by colinl** [comment] 2017-09-28 16:43
It's not the short name, you can configure that to anything, it is just the default text that appears with the icon.  As far as I can see the only difference having the file makes is that it stops it failing to connect when you first open the page from the icon.  I can't imagine what it is doing, it draws the page ok but does not connect. Perhaps it is loading from its cache but not running the javascript. I suspect it is a chrome bug.

**Comment by TotallyInformation** [comment] 2017-09-28 16:50
Oh, well you should get it anyway then because it exists in the master which should still be presented. I will need to test. Unfortunately, debugging anything on mobiles is a PITA.

Any chance you could remove your local manifest file and test using the following:
https://css-tricks.com/using-chrome-devtools-to-debug-javascript-in-any-browser-with-ghostlab-2/

to see if the manifest is being loaded? I expect it isn't from what you are saying even though it should be.

**Comment by colinl** [comment] 2017-09-30 19:44
I have made some progress. The default manifest file _is_ picked up when it is not provided. I think now the manifest file may just be a trigger, it seems it is not 100% reliable at forecasting failure, the inconsistent behaviour has proved very frustrating. However I have determined to some extent what is going on when it fails.
The javascript is being executed as normal, and it does run through the code 
   socket = io(ioNamespace, ...)
and ioNamespace is set to /home as it should be (in my case). However on('connect',..) is not called in the client and in the server debug I see absolutely nothing. I have also registered all the events in both the client and the server (connect error, error and so on) and  absolutely nothing is seen at either end.
As an experiment I added code in the client that watches for no connection, and if this persists for more than ten seconds then it runs
    socket.close()
    socket.open()
and so far this has proved fully reliable in persuading the connection to open.
Quite what this all means I don't know. The socket.close() is necessary, which suggests that it thinks the socket is already open.

**Comment by TotallyInformation** [comment] 2017-09-30 19:54
That's some excellent sleuthing Colin, thanks for that. I think that fits in with some cases I've seen previously where that has happened on the desktop too. Indeed, I think there is an entry under the known issues list in the README if I remember correctly. But I think that you have found a work-around which is brilliant and it would be great to get a pull request for it ;-)

I've spent some more time today looking at front-end libraries but in the process I found out how to allow Node-RED to send to a specific client instance. So that is in the updated source that I haven't pushed yet along with a load of README tidy ups and some minor tweaks to the master templates.

I've also decided that it would be best to automatically copy over the templates when a new end point is defined (e.g. a new node instance or changed URL) so that the code is more easily available to users. Also allows me to kill off a static path. I want to put that code in before I push a new version.

**Comment by colinl** [comment] 2017-09-30 20:03
How long do you think I should wait before trying to connect?
I think I will add some logic so that it only runs on initial startup, and is disabled once it connects the first time. Otherwise on a phone it might keep waking it up every few seconds to try and reconnect if the network (or server) were down, and might run the battery down.

**Comment by TotallyInformation** [comment] 2017-09-30 20:06
Have a look at the initial connection code. That has some reconnect logic already and it uses an extending timeframe.

**Comment by colinl** [comment] 2017-09-30 20:10
Do you mean the code starting
// A workaround for SIO's failure to reconnect after a NR redeploy of the node instance

**Comment by TotallyInformation** [comment] 2017-09-30 20:12
That sounds right. I'm not at my computer right now.

**Comment by colinl** [comment] 2017-09-30 20:40
Have a look at that code when you are at the computer, I am not sure it does what it is supposed to. It looks as if it is supposed to retry after 2 secs, then 3 secs, etc, but I think it only does it once. I think it needs a while !connected loop around it.

**Comment by TotallyInformation** [comment] 2017-10-01 15:37
Thanks for the pull. As mentioned there, I've manually merged your code as the source has changed somewhat. I've been testing as best I can and it seems to work. Though I added another call to the function on disconnect, placing my code (above) that, as you say, isn't quite working properly.

**Comment by TotallyInformation** [comment] 2017-10-01 20:21
OK, I've pushed v0.4.0 to GitHub (not published to NPM) if you want to try it. Your pull requests are merged. Note the change that copies the master template files over to the local folder when Node-RED restarts. It doesn't overwrite anything so if you want to revert to the master version, simply delete your local version and restart NR. You can delete 1 or more of the files at will.

**Comment by TotallyInformation** [comment] 2017-10-01 20:22
Next task will be to add an event system so that I can completely separate out the core logic in the front-end and make life easier for users.

**Comment by colinl** [comment] 2017-10-02 16:28
Version 0.4.0 working well for me.
Just a couple of trivia.
In uibuilder.js socket.on('error'..) hasn't got a log.debug statement. Is that intentional or an oversight?
In index.js retryMs is now redundant.
pazguille/jvent looks pretty good, simple to use but I can't see anything obvious missing. It hasn't had any activity recently but I don't suppose there is much required.

**Comment by TotallyInformation** [comment] 2017-10-03 08:45
Thanks Colin. I will tidy up the code. I've changed the error report to use log.error and I've created a factor variable as well as retryMs and used both of those when calling the function. I shan't bother to push to GH just now as those don't make any material change. 

Now I just need to find time and energy to get the event system in place.

**Closed** 2017-10-05 16:19 UTC
Labels: Fixed
