### ISSUE TITLE
Errors installing different nodes after install uibuilder

### ISSUE THREAD

**Issue by bakman2** [TotallyInformation/node-red-contrib-uibuilder#55] opened 2019-04-25 16:19 UTC
Installed uibuilder via `manage palette`, trying to install different nodes afterwards, they all fail with these messages:
 ```
2019-04-25T16:12:38.930Z [err] npm
2019-04-25T16:12:38.931Z [err]  ERR! path /home/pi/.node-red/node_modules/node-red-contrib-uibuilder
2019-04-25T16:12:38.931Z [err] npm ERR! code
2019-04-25T16:12:38.931Z [err]  EISGIT
2019-04-25T16:12:38.935Z [err] npm
2019-04-25T16:12:38.935Z [err]  ERR! git /home/pi/.node-red/node_modules/node-red-contrib-uibuilder: Appears to be a git repo or submodule.
2019-04-25T16:12:38.935Z [err] npm ERR! 
2019-04-25T16:12:38.935Z [err] git     /home/pi/.node-red/node_modules/node-red-contrib-uibuilder
2019-04-25T16:12:38.936Z [err] npm
2019-04-25T16:12:38.936Z [err]  ERR! 
2019-04-25T16:12:38.936Z [err] git Refusing to remove it. Update manually,
2019-04-25T16:12:38.936Z [err] npm
2019-04-25T16:12:38.936Z [err]  ERR! git
2019-04-25T16:12:38.937Z [err]  or move it out of the way first.
```

Versions:
```
25 Apr 18:11:26 - [info] Node-RED version: v0.20.5
25 Apr 18:11:26 - [info] Node.js  version: v10.15.3
25 Apr 18:11:26 - [info] Linux 4.14.98-v7+ arm LE (Raspb 3B - raspbian stretch)
```

Removed uibuilder, can install different nodes again without errors.

**Comment by doudalidou** [comment] 2019-04-26 03:11
Same here !

Please, remove the .git file from the distrib: cause it's always reappearing.

I've tried from the palette and the command line.

**Comment by colinl** [comment] 2019-04-26 06:03
Isn't that a problem that has been fixed in later versions of npm?

Colin

**Comment by bakman2** [comment] 2019-04-26 06:08
In my case:
```
npm -v
6.9.0
```
Perhaps @TotallyInformation can chime in.

**Comment by colinl** [comment] 2019-04-26 07:09
After some research I think I was wrong.  @doudalidou is correct, I believe the solution is to remove (or rename) the `.git` folder in `/home/pi/.node-red/node_modules/node-red-contrib-uibuilder`.  It should not be there.

**Comment by TotallyInformation** [comment] 2019-04-26 17:15
Hi, sorry been v. busy this week. 

Sorry, I'm confused. I can't see a .git file or folder in the repo?

.git folders are not copied when you push back to a branch and it certainly isn't there on the GitHub repo. Unless something has gone wrong with the `npm publish` process?

**Comment by bakman2** [comment] 2019-04-27 07:04
Well something goes wrong, I can't use uibuilder at this stage.

**Comment by colinl** [comment] 2019-04-27 07:12
@bakman2 is there a .git folder in the location indicated in the error message?

**Comment by bakman2** [comment] 2019-04-27 07:24
Installed uibuilder again, succesfull.
Tried to remove another node, failed with the same error above.

.git folder exists.
```
pi@raspberrypi:~/.node-red/node_modules/node-red-contrib-uibuilder $ ls -la
total 136
drwxr-xr-x   7 pi pi  4096 Apr 27 09:21 .
drwxr-xr-x 360 pi pi 12288 Apr 27 09:21 ..
drwxr-xr-x   2 pi pi  4096 Apr 27 09:21 bin
-rw-r--r--   1 pi pi 25243 Oct 26  1985 CHANGELOG.md
-rw-r--r--   1 pi pi  3233 Oct 26  1985 CODE_OF_CONDUCT.md
-rw-r--r--   1 pi pi   707 Oct 26  1985 .editorconfig
-rw-r--r--   1 pi pi   406 Oct 26  1985 .eslintrc.json
drwxr-xr-x   2 pi pi  4096 Apr 27 09:21 examples
drwxr-xr-x   3 pi pi  4096 Apr 27 09:21 .git
-rw-r--r--   1 pi pi   385 Oct 26  1985 .gitattributes
drwxr-xr-x   2 pi pi  4096 Apr 27 09:21 .github
-rw-r--r--   1 pi pi 10175 Oct 26  1985 LICENSE
drwxr-xr-x   5 pi pi  4096 Apr 27 09:21 nodes
-rw-r--r--   1 pi pi  3482 Apr 27 09:21 package.json
-rw-r--r--   1 pi pi 32888 Oct 26  1985 README.md
-rw-r--r--   1 pi pi   109 Oct 26  1985 TODO.md
pi@raspberrypi:~/.node-red/node_modules/node-red-contrib-uibuilder $ cd .git
pi@raspberrypi:~/.node-red/node_modules/node-red-contrib-uibuilder/.git $ ls -l
total 4
drwxr-xr-x 2 pi pi 4096 Apr 27 09:21 hooks
pi@raspberrypi:~/.node-red/node_modules/node-red-contrib-uibuilder/.git $ cd hooks
pi@raspberrypi:~/.node-red/node_modules/node-red-contrib-uibuilder/.git/hooks $ ls -l
total 4
-rw-r--r-- 1 pi pi 177 Oct 26  1985 README.sample
pi@raspberrypi:~/.node-red/node_modules/node-red-contrib-uibuilder/.git/hooks $ more README.sample
#!/bin/sh
#
# Place appropriately named executable hook scripts into this directory
# to intercept various actions that git takes.  See `git help hooks` for
# more information.
pi@raspberrypi:~/.node-red/node_modules/node-red-contrib-uibuilder/.git/hooks $
```

**Comment by colinl** [comment] 2019-04-27 07:43
@bakman2 is correct.  Installing from Manage Palette does install a .git folder.  Then you can't uninstall it.
It can't then be removed either.  Even after removing the .git folder it would not remove using `npm remove` though there was no error, it didn't say `removed n packages` though. I had to manually remove it from package.json then use `npm remove` to get it to actually take it out.  Very odd.

**Comment by TotallyInformation** [comment] 2019-04-27 08:07
OK, I've got it now, I can reproduce. But this is strange since I've never seen this before.

Sorry about this. Until I can sort it out, can I please ask that you install v1.2.2?

    npm install node-red-contrib-uibuilder@1.2.2

If you cannot uninstall uibuilder, just delete the folder:

    ~/.node-red/node_modules/node-red-contrib-uibuilder

I think that I am going to revert back to that release as something has gone seriously wrong with what I thought was a simple bug-fix. Apologies to all for messing you about.

**Comment by TotallyInformation** [comment] 2019-04-27 09:33
v1.2.2 is now published on npm as the `latest` tag. The `master` branch is reverted to v1.2.2

**Closed by TotallyInformation** 2019-04-27 09:33 UTC
Labels: bug

**Comment by realsquash** [comment] 2019-07-28 21:42
On a brand new blank install today this error popped up again and the git files are there.

**Comment by TotallyInformation** [comment] 2019-08-03 17:12
What version of the node is showing please?

**Comment by TotallyInformation** [comment] 2019-08-03 17:22
I've just manually downloaded and checked the npm latest version

```
pi@pi3:~/temp $ npm view node-red-contrib-uibuilder

node-red-contrib-uibuilder@1.2.2 | Apache-2.0 | deps: 7 | versions: 29
Easily create web UI's for Node-RED using any (or no) front-end library. JQuery and normalize.css included by default but change as desired.
https://github.com/TotallyInformation/node-red-contrib-uibuilder

keywords: node-red, ui, gui, dashboard

bin: bintest.js

dist
.tarball: https://registry.npmjs.org/node-red-contrib-uibuilder/-/node-red-contrib-uibuilder-1.2.2.tgz
.shasum: b2f6dd88d9ca9c03a0b35772841e1ea29425c510
.integrity: sha512-Mf8IFmo2eMWo9tL3OZqSh3VpKNFpDjiozKBFdGyPRcLMtCjg6ca4RvjhD8x12G6bqndWoGsG/RSMAlYe9Ksi0Q==
.unpackedSize: 260.7 kB

dependencies:
fs-extra: ^7.0.1           jquery: ^3.3.1             serve-static: ^1.13.2      winston: ^2.4.4
get-installed-path: ^4.0.8 normalize.css: ^8.0.1      socket.io: ^2.2.0

maintainers:
- totallyinformation <jk.npm@totallyinformation.com>

dist-tags:
latest: 1.2.2

published 4 months ago by totallyinformation <jk.npm@totallyinformation.com>
pi@pi3:~/temp $ wget https://registry.npmjs.org/node-red-contrib-uibuilder/-/node-red-contrib-uibuilder-1.2.2.tgz
--2019-08-03 18:20:04--  https://registry.npmjs.org/node-red-contrib-uibuilder/-/node-red-contrib-uibuilder-1.2.2.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 104.16.23.35, 104.16.22.35, 104.16.21.35, ...
Connecting to registry.npmjs.org (registry.npmjs.org)|104.16.23.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 76499 (75K) [application/octet-stream]
Saving to: ‘node-red-contrib-uibuilder-1.2.2.tgz’

node-red-contrib-uibuilder-1.2.2.tgz      100%[=====================================================================================>]  74.71K  --.-KB/s    in 0.02s

2019-08-03 18:20:05 (3.78 MB/s) - ‘node-red-contrib-uibuilder-1.2.2.tgz’ saved [76499/76499]

pi@pi3:~/temp $ unpack node-red-contrib-uibuilder-1.2.2.tgz
-bash: unpack: command not found
pi@pi3:~/temp $ tar -xzvf node-red-contrib-uibuilder-1.2.2.tgz
package/package.json
package/.editorconfig
package/.eslintrc.json
package/.gitattributes
package/CHANGELOG.md
package/CODE_OF_CONDUCT.md
package/LICENSE
package/README.md
package/TODO.md
package/.github/CONTRIBUTING.md
package/.github/issue_template.md
package/.github/PULL_REQUEST_TEMPLATE.md
package/bin/bintest.js
package/examples/cachetest.json
package/examples/moonEx2.json
package/nodes/icons/ui_template.png
package/nodes/src/images/node-blue-192x192.png
package/nodes/src/images/node-blue.ico
package/nodes/src/images/node-red.ico
package/nodes/src/index.html
package/nodes/src/uibuilderfe.js
package/nodes/src/uibuilderfe.min.js
package/nodes/templates/jquery/index.css
package/nodes/templates/jquery/index.html
package/nodes/templates/jquery/index.js
package/nodes/templates/jquery/manifest.json
package/nodes/templates/jquery/uibuilder.appcache
package/nodes/tilib.js
package/nodes/uiblib.js
package/nodes/uibuilder.html
package/nodes/uibuilder.js
pi@pi3:~/temp $
```

Everything is correct.

**Comment by realsquash** [comment] 2019-08-03 17:58
uibuilder:busgui: UI Builder Version 1.2.5 started at URL /busgui

**Comment by TotallyInformation** [comment] 2019-08-03 18:59
There was a bit of a cock-up where I had to downgrade. Probably the easiest thing to do will be to use the command line:

```
cd ~/.node-red
npm remove node-red-contrib-uibuilder
npm install node-red-contrib-uibuilder@latest
```

Then restart Node-RED and reload the admin ui. You should then have the correct version. One other thing you could do to make doubly sure would be to check your package.json file after uninstalling uibuilder to make sure that it isn't still listed in the dependencies.

After reinstallation, you should find that all of your deployed nodes and custom code are still in place as the installation will not overwrite anything.

Apologies for the confusion.

**Comment by TotallyInformation** [comment] 2019-08-06 15:28
@realsquash, turns out this is not a problem on your end but rather a problem with the Node-RED Flows site (which is also used by the Node-RED Palette Manager). It has picked up the wrong version.

You should install from the command line to get the correct version:

```
cd ~/.node-red
npm install node-red-contrib-uibuilder@1.2.2
```

**Comment by TotallyInformation** [comment] 2019-08-06 18:03
The version on the flows site is now correct so you should be able to remove and reinstall via the palette manager if you like.
